### ISSUE TITLE
Asset Store Package

### ISSUE THREAD

**Issue by bzaPetey** [WatchBeam/interactive-unity-plugin#3]
Can not import the Unity Asset Store package to any projects, even a freshly created one. Getting the following error:
Failed to import package with error: Couldn't decompress package
UnityEditor.Web.JSProxyMgr:DoTasks()

**Comment by bzaPetey** [comment]
BeamManager.SingletonInstance.TriggerCooldown("joinGame", 3000); will trigger the cooldown the first time. After the cooldown is done, clicking it again will not trigger the cooldown again. In the debug msg, the only error I see is about the etag not matching.

**Comment by payzer** [comment]
Thank you for filing this. Does this error go away after you close and re-open Unity?

**Comment by payzer** [comment]
Thank you for the extra context. I looked around for that call and unfortunately it's in the editor itself. The behavior is a bug with the Unity editor so we won't be able to fix it on our side. 
In case it helps (it may not), we also host the latest version of the plugin in this repro's releases section: https://github.com/WatchBeam/interactive-unity-plugin/releases

You can import it Assets > Import Package > Custom Package... and browse to the .unitypackage file.

Some of the posts on the Unity forums said waiting longer even after the dialog goes away may help.

I'll close the issue since it's in the Unity Editor. Sorry for the frustrating error.
